frontend/tsconfig.json

- close #50 
`tsconfig` 에 `esModuleInterop: true`로 설정

Fix: tsconfig에 esModuleInterop: true로 설정

---

frontend/.storybook/main.ts
frontend/.storybook/preview.tsx
frontend/package-lock.json
frontend/package.json
frontend/src/apis/dictionary.ts
frontend/src/apis/search.ts
frontend/src/components/SearchBox/SearchBox.style.ts
frontend/src/components/SearchBox/index.tsx
frontend/src/hooks/useDebounce.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/storybookHandlers.ts
frontend/src/pages/Main/Main.style.tsx
frontend/src/queries/dictionaryPlants.ts

- close #89 
- close #64 
- api 명세 변경에 따른 msw 및 apis 수정
- useQuery를 이용한 api 통신 훅
- 검색창에 해당 훅 적용
- useDebounce 구현 및 적용
- 일치하는 이름을 찾아 사전 정보 또는 유사 목록으로 이동하는 콜백
- 스토리북 라우터 설정
fetcher는 apis 폴더에,
서버 상태 관리는 queries 폴더에 넣는 방향으로 구현하였습니다.
컴포넌트에서는 본인이 필요한 훅을 queries에서 불러오기만 하면 되기 때문에 간편해요
fetcher와 react query 로직을 분리해 놓았기 때문에 나중에 axios로 갈아탄다면 고치기 유리해요
파일명은 나중에 의논해보면 좋을 것 같아요
이런 방식의 분할이 어떨지 여러분의 의견이 궁금해요 👍

feat: 메인 페이지 검색 기능 고도화

---

backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
backend/pium/src/main/java/com/official/pium/domain/Auth.java
backend/pium/src/test/java/com/official/pium/RepositoryTest.java
backend/pium/src/test/java/com/official/pium/UITest.java
backend/pium/src/test/java/com/official/pium/repository/DictionaryPlantRepositoryTest.java
backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java

- close #98 
-  MemberArgumentResolver에서 Member 클래스와 Auth 어노테이션 유무를 확인합니다.
- MemberArgumentResolver에서 Authorization 헤더를 확인합니다.
인증이 필요한 부분에 누락된 사항이 없는지 확인 부탁드립니다.

refactor: 사용자 인증방식 추가

---

.github/workflows/frontend-dev.yml
frontend/src/components/@common/ProgressBar/ProgressBar.stories.tsx
frontend/src/components/@common/ProgressBar/ProgressBar.style.ts
frontend/src/components/@common/ProgressBar/index.tsx
frontend/src/components/FormInput/index.tsx
frontend/src/components/SearchResults/index.tsx
frontend/src/hooks/useDictrionaryNavigate.ts
frontend/src/pages/DictionarySearch/DictionarySearch.style.ts
frontend/src/pages/DictionarySearch/index.tsx
frontend/src/pages/Main/index.tsx
frontend/src/pages/PetRegister/Form/Form.style.ts
frontend/src/pages/PetRegister/Form/index.tsx
frontend/src/router.tsx

- close #128 
- 폼 입력 다 하면 Stack을 이용해서 맨 위에도 완료 버튼을 보여줍니다.
맨 밑에 버튼을 없애지 않은 이유는 1. 폼 미완일 때 미완임을 명시하기 위함 2. 사용자가 재확인을 위해 아래로 이동했을 때도 바로 등록 가능하게 하기 위함입니다.
- 검색 결과 페이지에서 검색어를 표시합니다.
- generatePath 적용했습니다. 쿼리스트링 쪽도 한번 해봤는데 안되더라구요ㅠ 일단 거기는 냅뒀습니다
- 버튼 접근성 개선: Button 태그에 onClick을 다는 방향으로 리팩터링 진행했어요
- 현재 배포 서버에서도 나오는 현상인데 식물 등록할 때 검색 후 식물 선택하면 앱이 터집니다.
- 원인: useQuery의 suspense가 true인데 suspense가 없어서
- 해결: suspense 대충 추가
**제가 시간 내서 Cypress 전격 도입하겠습니다**

refactor: 식물 사전 검색 결과 리팩터링, 데모데이 피드백 반영, 버그 수정

---

backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
backend/pium/src/main/java/com/official/pium/service/ReminderService.java
backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java

- close #171 
리마인더 조회 시, 반려 식물의 `다음 물주기 날짜` 기준으로 오름차순 정렬하여 응답하도록 수정하였습니다.  
예시로 응답의 `nextWaterDate` 만 생각하면 아래와 같은 순서입니다.
```
2023-07-01,
2023-07-02,
2023-07-10,
2023-08-10
...
```
코드 자체는 많이 변경된 사항은 없어서 전체적으로 봐주세요. 감사합니다!

refactor: 리마인더 조회 정렬 추가

---

backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
backend/pium/src/main/resources/sql/schema.sql
backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
backend/pium/src/test/java/com/official/pium/config/DatabaseCleaner.java
backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java

- close #220 
반려 식물 삭제 기능을 구현했습니다 !
- 수정과 마찬가지로 반려 식물의 주인을 확인하는 로직을 추가했습니다.
- 현재 구현하는 `반려 식물 삭제`는 무덤과는 관계없이 완전히 서비스에서 삭제하므로, `관련 히스토리까지 삭제`하도록 구현했습니다.
- 삭제 기능의 인수 테스트를 명확히 하기 애매했던 것 같아요 🥹 그래서 `등록 -> 삭제 -> 조회 시 없음`의 과정을 인수 테스트로 작성했습니다. 관련해서 의견 남겨주시면 좋을 것 같아요 :)

feat: 반려 식물 삭제 기능 구현

---

frontend/cypress/e2e/navbar.cy.ts
frontend/src/components/@common/Navbar/Navbar.stories.tsx
frontend/src/components/@common/Navbar/Navbar.style.ts
frontend/src/components/@common/Navbar/index.tsx
frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
frontend/src/pages/DictionaryDetail/DictionaryDetail.style.ts

- close #226 
- close #200 
- close #203 
- navbar position fixed로 변경
- 반려 식물 상세 정보 하단 margin 추가
- 식물 사전 정보 하단 margin 추가
- 주석처리했던 달력 관련 이동 로직 제거
- 페이지 이동 기능 e2e 테스트 작성

refactor: 내비게이션 바 리팩터링과 cypress 테스트

---

frontend/src/components/@common/Calendar/Calendar.style.ts
frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts
frontend/src/components/@common/Calendar/DaySmallBox/index.tsx
frontend/src/components/@common/Calendar/index.tsx
frontend/src/components/@common/DateInput/DateInput.stories.tsx
frontend/src/components/@common/DateInput/index.tsx
frontend/src/components/petPlant/PetPlantCard/PetPlantCard.stories.tsx
frontend/src/components/petPlant/PetPlantEditForm/index.tsx
frontend/src/components/reminder/Card/index.tsx
frontend/src/constants/index.ts
frontend/src/hooks/useDateInput.ts
frontend/src/hooks/useModal.ts
frontend/src/hooks/useNumberInput.ts
frontend/src/hooks/usePetPlantForm.ts
frontend/src/mocks/storage/PetPlant.ts
frontend/src/pages/PetRegister/Form/index.tsx
frontend/src/types/date.ts
frontend/src/types/history.ts
frontend/src/types/petPlant.ts
frontend/src/types/reminder.ts
frontend/src/utils/date.ts
frontend/src/utils/validate.ts

- close #230 
- 오늘이 선택 불가능한 날일 경우 흐리게 표시
- 달력 월 이동을 날짜 제한 밖으로 벗어날 수 없게 설정
- 선택 가능한 날에 마우스 hover 시 표시
- 선택 불가능한 날 cursor default
- 최대/최소 날짜 제한 기본값 추가 (1945년 ~ 2099년)
- 모달 배경 클릭 시 닫기
- 1900년 1월 1일부터 2099년 12월 31일까지 가능
- 범위를 이렇게 설정한 이유는 2100년대도 추가하면 타입이 너무 복잡하다고 빨간줄을 띄우더라구요
- 연월일을 `-`로 표현하는 타입과 `년 월 일` 한글로 표현하는 타입 두 가지를 만들었습니다
- 해당 타입에 대해 타입 가드도 만들어서 적용했어요

refactor: 달력, 모달, 그리고 DateFormat

---

backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java
backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java

- close #218 
반려 식물을 등록할 때 최초 히스토리 로그가 총 여섯 개 추가됩니다.
`PetPlantService`의 create 메소드 봐주시면 되겠습니다.

feat: 반려식물 등록 시 히스토리 추가

---

frontend/src/components/@common/ContentHeader/ContentHeader.stories.tsx
frontend/src/components/@common/ContentHeader/ContentHeader.style.ts
frontend/src/components/@common/ContentHeader/index.tsx
frontend/src/components/@common/VerticalDivider/VerticalDivider.style.ts
frontend/src/pages/MyPage/MyPage.style.ts
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/PetPlantCardList/PetPlantCardList.style.ts
frontend/src/pages/PetPlantCardList/index.tsx
frontend/src/pages/Reminder/Reminder.style.ts
frontend/src/pages/Reminder/index.tsx
frontend/src/style/Global.style.ts

- close #329 
마이 페이지에 있는 회원 탈퇴 버튼을 아래에 삽입했습니다. 
그리고 리마인더, 마이페이지, 내 식물 보기의 콘텐츠 헤더가 모두 다른 것 같아서 하나로 통일하기 위해 `contentHeader`라는 컴포넌트를 만들었습니다. 
1. 회원 탈퇴 버튼의 위치에 대한 생각
2. 공통적으로 만든 콘텐츠 헤더에 대한 생각
3. `verticalDivider`라는 컴포넌트를 살짝 만들었는데, 해당 컴포넌트에 넘기는 파라미터의 타입을 한번 봐주시면 감사하겠습니다.

refactor: 마이페이지 회원 탈퇴 버튼 위치를 수정한다.

---

backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
backend/pium/src/test/java/com/official/pium/controller/AdminPageControllerTest.java

- close #352 
누락된 사항이 있나 확인부탁드립니다.

fix: 정적파일 경로 수정

---

frontend/src/apis/dictionaryPlantRegistration.ts
frontend/src/components/search/SearchBox/SearchBox.style.ts
frontend/src/components/search/SearchBox/index.tsx
frontend/src/constants/index.ts
frontend/src/pages/NewDictionaryPlantRequest/Form/index.tsx
frontend/src/utils/image.ts

- close #359 
- formdata를 보낼 때, JSON은 `request` 안에, 이미지는 `image` 안에 담아서 보내는 컨벤션에 맞춰 변경했어요
- 검색창에서 등록 신청하기를 두 줄로 바꿨어요
- 이미지 확장자를 jpg, jpeg, png, heic만 받도록 제한했어요

refactor: 사전 식물 등록 신청 FormData 컨벤션을 맞춘다.

---

.github/workflows/frontend-e2e-test.yml
frontend/cypress/e2e/auth.cy.ts
frontend/src/components/@common/Image/Image.style.ts
frontend/src/components/@common/Image/index.tsx
frontend/src/components/petPlant/PetPlantCard/index.tsx
frontend/src/components/search/SearchBox/index.tsx
frontend/src/utils/image.ts

- close #381
- sharp 사용
- small: 가로 256px
- x-small: 가로 64px
```js
import Sharp from 'sharp'; // 이 패키지는 npm으로 설치가 필요해요
import fs from 'fs';
import { join } from 'path';
const SMALL = {
width: 256,
};
const X_SMALL = {
width: 64,
};
const INPUT_DIR = './static';
const OUTPUT_DIR = './output';
const getFileNames = (dir) => fs.readdirSync(dir);
const convertImageTo = async (filename, width, type, format) => {
const inputPath = join(INPUT_DIR, filename);
const filenameWithoutExt = filename.split('.')[0];
const sharp = new Sharp(inputPath);
const { width: imageWidth } = await sharp.metadata();
if (imageWidth <= width) {
console.log(`${filename} image width(${imageWidth}) is smaller than target size(${width}).`);
return false;
}
await sharp
.resize(width)
.toFormat(format.toLowerCase(), { …
```

refactor: 사전 식물 이미지 해상도를 조정한다

---

frontend/src/components/@common/Image/index.tsx
frontend/src/constants/index.ts
frontend/src/hooks/image/useFileUpload.ts
frontend/src/mocks/data/dictionaryPlant.ts
frontend/src/mocks/data/garden.ts
frontend/src/mocks/data/petPlantCardList.ts
frontend/src/mocks/data/petPlants.ts
frontend/src/mocks/data/reminder.ts
frontend/src/mocks/data/search.ts
frontend/src/utils/image.ts

- close #389 
`https://pium.static.life`로 시작하는 url만 해상도 변환 로직을 적용하게끔 바꿨습니다. 어차피 사진 해상도 이름 규칙은 저희끼리만 쓰는거라서 아예 외부 요청에 대해서는 검사조차 하지 않게 설정했어요
사용자가 사진을 올리면 `blob:https://pium.life/어쩌구` 이런식의 주소가 되어버려서 요 상황에서 바뀐 해상도를 요청하는 것을 막고자 하는 목적도 있습니다
- 원인
useRef 안에 맨 처음에 받은 src를 이용한 주소들을 가뒀기 때문에 이후에 url이 바뀌어도 ref의 내용물이 변하지 않아서 보여주는 값은 예전 사진이었어요
- 해결
useRef를 없앴습니다. 기본적으로 Image 컴포넌트 자체의 작동 방식이 (src를 직접 건드려서) 비제어 컴포넌트와 유사하다고 생각했기 때문에 지웠는데 큰 문제는 보이지 않았어요
- 기존
- 변경
이제 로컬에서도 변환된 사진을 잘 받아오는지 확인이 가능합니다. 아카시아는 일부러 없는 url을 넣었어요.

fix: 사용자 사진 업로드 시 미리보기가 안 바뀌는 문제

---

backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
backend/pium/src/main/java/com/official/pium/service/PhotoManager.java
backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
backend/pium/src/test/java/com/official/pium/util/PhotoS3ManagerTest.java

- close #406 
반려 식물 수정 시 기존 이미지가 정상적으로 제거되도록 경로 추가했습니다. 
수정하면서 테스트도 조금 보완했습니다.
혹시 더 필요한 테스트가 있으면 알려주세여~

fix: 반려 식물 수정 시 기존 이미지 제거

---

frontend/src/components/@common/Image/index.tsx
frontend/src/mocks/data/reminder.ts
frontend/src/models/ImageSourceList.ts

- close #420 
- 주어진 사진 url을 받아 적절한 저해상도 이미지 src 접근을 도와주는 `ImageSourceList` 클래스
- 전역 set을 사용해서 한 번 실패한 url은 새로고침 전에는 다시 시도하지 않습니다.
|전|후|
|:-:|:-:|
|페이지를 이동하면 이미지가 깜빡입니다.|첫 접속에만 이미지가 깜빡입니다|
|![image_problem_local](https://github.com/woowacourse-teams/2023-pium/assets/77872742/21186b66-6611-426f-85d0-57121d3ed201)|![image_problem_solved](https://github.com/woowacourse-teams/2023-pium/assets/77872742/ec521e56-f269-4d49-94d4-6cc61ff71ff2)|
class라서 일단 models에 넣었는데 괜찮은가요?

feat: 한 번 불러오기 실패한 사진은 다시 요청하지 않기

---

frontend/src/hooks/queries/auth/useLogin.ts
frontend/src/pages/auth/Login/Authorization.tsx

- close #431 
- 로그인 API method가 POST인데 tanstack-query에서는 useQuery를 사용하고 있었음
- 따라서 mutation으로 변경해서 API를 전송하도록 요청
- 그에 따라 useEffect를 통해 login메서드를 실행시킹
- 하지만 기존 Authorization 페이지에서는 바로 reminder로 이동하는 Navigator를 반환
- 즉, reminder페이지로 이동하고 로그인을 요청하는 상황이 발생해벌암;;
- Authorization에서 Navigator를 반환하던 것을 Loading을 반환하도록 함
- 그리고 Mutation에서 SuccessCallback으로 로그인에 성공했을 경우 reminder로 navigate하도록 설정
- 반면 실패했을 때는 에러 메세지와 함께 로그인 페이지로 이동하도록 작성함.
잘 부탁드립니당

Fix: 로그인 되지 않던 이슈 해결

---

backend/pium/src/main/resources/templates/admin/member/requests.html

docs: 사용자 목록 페이지 수정

---

backend/pium/src/main/java/com/official/pium/service/MemberService.java
backend/pium/src/main/java/com/official/pium/service/dto/NotificationSubscribeRequest.java
backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java
backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java

fix: 알림 등록 요청 변수명 변경 deviceToken -> token

---

backend/pium/src/main/java/com/official/pium/controller/AuthController.java
backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
backend/pium/src/test/java/com/official/pium/UITest.java
backend/pium/src/test/java/com/official/pium/acceptance/GardenApiTest.java
backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
backend/pium/src/test/java/com/official/pium/controller/GardenControllerTest.java
backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java

- close #452 
ArgumentResolver에서 HttpSession을 통해 sessionId를 가져오는 것을, 최초의 request인 NativeRequest에서 가져오도록 변경했습니다.
쿠키에서 세션 ID를 파싱하고 있는데 해당 로직 한번 확인해주세요 !

fix: 요청 발생 시 HttpSession 제거하도록 변경

---

backend/pium/src/main/java/com/official/pium/controller/AuthController.java
backend/pium/src/main/java/com/official/pium/controller/MemberController.java
backend/pium/src/main/java/com/official/pium/exception/AuthorizationException.java
backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
backend/pium/src/main/java/com/official/pium/service/MemberService.java
backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java

- close #454 
`/members/me`, `/logout`, `/withdraw` 등 사용자 세션을 다루는 API에서 WAS Session을 사용하는 구문을 제거했습니다.
감사합니다.

fix: 메모리 세션 구문 제거

---

backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
backend/pium/src/test/java/com/official/pium/repository/SessionGroupRepositoryTest.java
backend/pium/src/test/java/com/official/pium/service/SessionGroupServiceTest.java

- close #460 
로그인 시 세션이 존재할 경우 예외를 던지는것이 아니라 정상 반환하도록 수정했습니다.

fix: 로그인 시 세션이 존재할 경우 정상 반환
