frontend/.eslintrc
- close #7 
- webpack.config.js
- mockServiceWorker.ks
-
=> fix: eslint ignorePatterns 추가

backend/pium/.gitignore, backend/pium/src/main/java/com/official/pium/PiumApplication.java, backend/pium/src/main/java/com/official/pium/domain/BaseEntity.java, backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java, backend/pium/src/main/java/com/official/pium/domain/Member.java, backend/pium/src/main/java/com/official/pium/domain/PetPlant.java, backend/pium/src/main/java/com/official/pium/domain/WaterCycle.java, backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java, backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java, backend/pium/src/main/resources/application.properties, backend/pium/src/main/resources/sql/schema.sql, backend/pium/src/test/java/com/official/pium/repository/DictionaryPlantRepositoryTest.java, backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java, backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
=> feat: 데이터베이스 스키마 구성

frontend/tsconfig.json
- close #35 
tsconfig에 절대경로를 추가해 줬습니다.
=> build: tsconfig에 webpack alias 절대경로 추가

backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java, backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
- close #37 
- PetPlant, Member, DictionaryPlant Repository의 접근 제어자를 선언했습니다.
- 감사합니다
=> fix: Repository 인터페이스 접근 제어자 추가

.github/workflows/backend-dev.yml
- close #40
백엔드 Github Actions workflow 작성
컴파일 에러는 없는지 한번 더 확인해주세요.
=> build: 백엔드 CI workflow 추가

.husky/commit-msg, .husky/pre-commit, frontend/package-lock.json, frontend/package.json
- close #9 
husky 설치를 통해 commit 할 경우에 메세지 켄벤션 지키도록 설정
만약에 적용이 되지 않는다면 `npx husky install` 한반 할 것.
=> chore: husky 설정

backend/pium/build.gradle
Gradle 파일의 version을 제거했습니다.
감사합니다.
=> build: Gradle 빌드 결과물 버전 제거

frontend/.storybook/main.ts, frontend/.storybook/preview.ts, frontend/package-lock.json, frontend/package.json, frontend/src/pages/Root/Root.style.tsx, frontend/src/style/styles.d.ts, frontend/src/style/theme.style.ts
- close #55 
- mobile 크기 : 360 x 800으로 설정
- tablet 크기: 768. x 1024 (Ipad)로 설정
`theme-provider`에 width 객체 생성 (모바일, 패드 크기 지정)
.
=> chore: 스토리북 view port addon 적용

backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java, backend/pium/src/main/java/com/official/pium/mapper/DictionaryPlantMapper.java, backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java, backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java, backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java, backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantSearchResponse.java, backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java, backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java, backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
- close #16 
DictionaryPlantService의 search 메소드 중점적으로 봐주시면 좋을 것 같아요!
=> feat: 사전 식물 검색기능 구현

frontend/src/components/Select/Select.stories.tsx, frontend/src/components/Select/Select.style.ts, frontend/src/components/Select/index.tsx, frontend/src/style/styles.d.ts, frontend/src/style/theme.style.ts
- close #74
셀렉터를 구현했습니다!
누르면 화살표가 돌아가요
제어 컴포넌트인지라 우선 `value` 와 `onChange` 를 받아서 핸들링 하도록 설계했습니다.
사용하는 예제를 스토리북에 General로 작성해 뒀어요.
어떤 방법으로 제어컴포넌트를 설계할지 이야기 해보면 좋을 것 같습니다.
=> feat: 셀렉터 구현

frontend/src/components/DateInput/DateInput.style.ts, frontend/src/components/FormInputBox/FormInputBox.stories.tsx, frontend/src/components/FormInputBox/FormInputBox.style.ts, frontend/src/components/FormInputBox/index.tsx, frontend/src/style/styles.d.ts, frontend/src/style/theme.style.ts, frontend/src/types/inputs.ts
- close #65 
입력 컴포너트를 children을 넘기는 방식으로 구현했습니다. 
폼과 관련한 컴포넌트인데 아직 폼에 대한 명확한 디자인이나 구현 방법이 나오지 않아서 컴팩트하게 구현만 하고, 이후에 폼을 만들면서 기능 등을 추가해야 할 것 같습니다.
전반적인 디자인에 대한 이야기를 해주시면 감사하겠습니다!
=> feat: 입력 폼 공통 컴포넌트 구현

frontend/package.json, frontend/src/components/Stack/Stack.stories.tsx, frontend/src/components/Stack/contexts/stackContext.tsx, frontend/src/components/Stack/hooks/useStackContext.ts, frontend/src/components/Stack/index.tsx, frontend/src/components/Stack/ingredients/Element.tsx, frontend/src/components/Stack/ingredients/Main.style.ts, frontend/src/components/Stack/ingredients/Main.tsx, frontend/src/constants/index.ts
- close #75 
컴파운드 컴포넌트로 만든 스택형 UI에요
사용법
```jsx
<Stack>
<Stack.Element height="50px">
<Profile />
</Stack.Element>
<Stack.Element height="200px">
<Image />
</Stack.Element>
</Stack>
```
<Stack.Element> 안에 쌓을 컴포넌트를 넣으면 돼요
height는 부드러운 애니메이션을 위해서 필수입니다
```ts
const { showNextElement, isLastElementShown } = useStackContext();
const handleClick = () => showNextElement();
```
컴포넌트 안에서 showNextElement를 호출하면 해당 컴포넌트의 바로 다음 요소가 나타나요.
만약 이미 나타나 있다면 아무 일도 일어나지 않아요
dist 안의 storybook 폴더로 빌드하도록 수정했어요
기능 구현: 1시간
CSS: 3시간
input 컴포넌트 내부에서 showNextElement 만으로 다음 요소를 나타내는 방식이 괜찮을지 고민됩니다.
=> feat: 스택형 UI 구현

frontend/.eslintrc, frontend/.storybook/preview.tsx, frontend/package-lock.json, frontend/package.json, frontend/src/index.tsx
- close #85 
1. 리액트 쿼리 설치
2. 리액트 쿼리 관련 eslint 설정 (recommended)
3. 리액트 쿼리를 App과 스토리북에서 사용 가능하게 설정
저희는 멋있게 v5 사용합니다.
공식 문서는 처음 접속하면 v4로 나오니 조심하세요 👍
=> chore: react-query 설정

backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java, backend/pium/src/main/java/com/official/pium/config/WebMvcConfigure.java, backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java, backend/pium/src/main/java/com/official/pium/service/dto/PetPlantRequest.java, backend/pium/src/test/java/com/official/pium/UITest.java, backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java, backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
- close #97 
임의의 회원 인증 기능 및 컨트롤러 테스트에 configuration 추가
감사합니다
=> Feature/97 임의의 회원 생성

.github/workflows/frontend-dev.yml
- close #106 
서칭 기반으로 작업이 되도록 한번 적용해 봤는데 실험은 해봐야 할 것 같긴합니다..
npm build와 storybook build 만 추가하는 형식으로 작성했고, 추후에 테스트가 추가된다면 이에 따라 추가적으로 작성될 예정입니다
=> build: frontend ci 작성

.github/workflows/frontend-dev.yml
- close #이슈번호
npm build 에러 나는 것 package-lock.json 경로 추가
=> build: package-lock 파일 위치 지정

.github/workflows/frontend-dev.yml
- 이름 변경
- 노드 설정 시 캐시 참고하지 않게 변경
=> build: 프론트엔드 빌드 테스트 yml 수정

.github/workflows/frontend-dev.yml
CI Result를 PR에 작성하는 코드를 삭제했습니다.
=> build: CI Result 구문 삭제

.github/workflows/frontend-dev.yml
continue-on-error 삭제로 실패하는 모든 테스트 체크안되게 설정
=> build: continue-on-error 삭제

backend/pium/src/main/java/com/official/pium/domain/History.java, backend/pium/src/main/resources/sql/schema.sql
=> build: 히스토리 테이블 추가

backend/pium/src/main/java/com/official/pium/domain/PetPlant.java, backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java, backend/pium/src/main/java/com/official/pium/service/PetPlantService.java, backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java, backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java, backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
- close #133 
테스트 빼먹은거 없는지 확인 부탁드려요~
=> refactor: 반려 식물 단건 조회 

.github/workflows/backend-dev.yml, .github/workflows/frontend-dev.yml
=> build: 트랙별 워크플로우 환경변수 구분

frontend/src/constants/index.ts, frontend/src/mocks/handlers.ts, frontend/src/mocks/storybookHandlers.ts
- close #152 
- https 추가
- env에 따른 base url 변환
로컬호스트에서 msw 끄고 테스트한 결과 https로 잘 보내지는 것을 확인했습니다
다만 스토리북의 경우 실제 서버에 올라갔을 때 msw 모킹이 잘 이루어질지는 잘 모르겠어요ㅠ
=> fix: API 서버 https 적용에 따른 BASE_URL 수정

frontend/src/components/@common/Icons/Calendar.tsx, frontend/src/components/@common/Icons/Home.tsx, frontend/src/components/@common/Icons/Plant.tsx, frontend/src/components/@common/Icons/Reminder.tsx, frontend/src/components/@common/Navbar/Navbar.stories.tsx, frontend/src/components/@common/Navbar/Navbar.style.ts, frontend/src/components/@common/Navbar/index.tsx, frontend/src/constants/index.ts, frontend/src/pages/DictionarySearch/DictionarySearch.style.ts, frontend/src/pages/DictionarySearch/index.tsx, frontend/src/pages/Main/Main.style.tsx, frontend/src/pages/Main/index.tsx, frontend/src/pages/PetRegister/Form/Form.style.ts, frontend/src/pages/PetRegister/Search/Search.style.ts, frontend/src/pages/PetRegister/Search/index.tsx, frontend/src/pages/Root/Root.style.tsx, frontend/src/pages/RootTemplate/RootTemplate.style.tsx, frontend/src/pages/RootTemplate/index.tsx, frontend/src/router.tsx
- close #101
네비게이션 바를 구현했습니다.
- #888888 이 정말 딱 이뻐서 이걸로 사용했습니다!
- position을 fix로 하면 너비가 main을 벗어나버려서 absolute로 했습니다. 그래서 main에도 relative를 추가했는데요, 
그냥 네비게이션 바에 min-witdh를 하드하게 주는게 나은지 고민이에요.
=> feat: 네비게이션 바 구현

backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java, backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java, backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
- close #159 
fixture 사용하는 부분 없는지 한번 더 확인해주시면 감사하겠습니다 !
=> refactor: 테스트 support에서 사용하던 fixture 제거

backend/pium/src/main/java/com/official/pium/controller/ReminderController.java, backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java, backend/pium/src/main/java/com/official/pium/domain/History.java, backend/pium/src/main/java/com/official/pium/domain/Member.java, backend/pium/src/main/java/com/official/pium/domain/PetPlant.java, backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java, backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java, backend/pium/src/main/java/com/official/pium/service/ReminderService.java, backend/pium/src/main/java/com/official/pium/service/dto/ReminderCreateRequest.java, backend/pium/src/main/java/com/official/pium/service/dto/ReminderResponse.java, backend/pium/src/main/java/com/official/pium/service/dto/ReminderUpdateRequest.java, backend/pium/src/test/java/com/official/pium/controller/ReminderControllerTest.java, backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java, backend/pium/src/test/java/com/official/pium/fixture/ReminderFixture.java, backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java, backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
- close #120 
- 리마인더 조회, 물주기, 미루기 기능 구현했습니다.
- 테스트 부분 놓치거나 부족한 게 없는지 봐주시면 좋을 것 같습니다.  
- 물주기, 미루기 메서드 네이밍 고민을 오래하긴 했는데, 그렇게 마음에 들진 않네요. 혹시 더 좋은 이름 있으면 추천 받습니다🥹 
- 리마인더 기능에 대한 세부적인 논의가 아직 이루어지고 있어서, 중간에 변경되는 부분들이 있을 것 같아요. 이 점 참고 부탁드립니다!
=> feat: 리마인더 기능 구현

.github/workflows/frontend-e2e-test.yml, frontend/cypress.config.ts, frontend/cypress/e2e/dictDetails.cy.ts, frontend/cypress/e2e/dictSearch.cy.ts, frontend/cypress/e2e/main.cy.ts, frontend/cypress/e2e/petRegister.cy.ts, frontend/cypress/e2e/spec.cy.ts, frontend/cypress/fixtures/example.json, frontend/cypress/support/commands.ts, frontend/cypress/support/e2e.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/SearchBox/SearchBox.style.ts, frontend/src/components/SearchBox/index.tsx, frontend/src/components/SearchResults/SearchResults.style.ts, frontend/src/components/SearchResults/index.tsx, frontend/src/components/Select/index.tsx, frontend/tsconfig.json
- close #131 
1. Cypress 설치
2. Github Actions yml 작성
- 조건: develop 또는 main 브랜치로 PR이 열렸거나, push가 되었을 때
- 하는 일: cypress test를 모두 돌려보고 실패했을 경우 슬랙에 알려줍니다
3. 테스트 코드 작성
- 메인 화면 검색창, 식물 등록 과정을 집중했어요
- 나머지 페이지는 그냥 열렸는지 확인하는 정도에 가까워요
4. 몇몇 코드 변경
- role을 추가해서 테스트할 때 컴포넌트를 잡아오기 편하게 했어요 (약간의 접근성은 덤)
- 같은 이유로 몇몇 컴포넌트에 의미 있는 태그를 적용했습니다
=> test: Cypress 자동화 테스트

frontend/src/apis/history.ts, frontend/src/mocks/handlers.ts
- close #188
history API 변경내용을 적용했습니다.
=> fix: 히스토리 api 변경

frontend/src/hooks/useCalendar.ts, frontend/src/utils/date.ts
- close #이슈번호
Date('YYYY-MM-DD') 형태로 처리하는 값들을 Date(yyyy,mm,dd)의 형태로 변경했습니다.
일부 메서드에서는 new Date를 통해서 값을 처리하는 것들이 있는데, 현재 화면에서는 크게 문제가 생기지 않아서 안되는 부분들만 급하게 처리했습니다.
=> fix: date 입력 형태 'YYYY-MM-DD' 형태에서 YYYY,MM,DD 형태로 변경

frontend/src/components/Reminder/Card/Card.style.ts, frontend/src/hooks/useCalendar.ts, frontend/src/mocks/data/reminder.ts, frontend/src/utils/date.ts
=> Hotfix/reminder 글자 길이 변경

frontend/src/components/PetPlantCard/index.tsx
=> fix: 생일을 월 일 기준으로 계산

.github/workflows/frontend-dev.yml
프론트엔드 모든 push에 대해 build 검사하지 않고 develop과 main에 merge하는 commit의 push에만 검사하도록 변경했습니다
(기존 PR에 새로운 commit이 올라왔을 때 다시 검사하는 것은 그대로입니다. 검사 두 번씩 하는 걸 없앴어요)
=> chore/github actions build test 조건 변경

frontend/.eslintrc, frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts, frontend/src/components/@common/DateInput/DateInput.stories.tsx, frontend/src/components/@common/FormInput/FormInput.stories.tsx, frontend/src/components/@common/FormInput/index.tsx, frontend/src/components/@common/Select/Select.stories.tsx, frontend/src/components/@common/Stack/Stack.stories.tsx, frontend/src/components/@common/Toast/Toast.stories.tsx, frontend/src/components/@common/Toast/index.tsx, frontend/src/hooks/useDictrionaryNavigate.ts, frontend/src/hooks/useModal.ts, frontend/src/hooks/usePetPlantForm.ts, frontend/src/pages/PetPlantTimeline/index.tsx, frontend/src/pages/PetRegister/Form/index.tsx
- close #249  
- eslint react-hooks recommended 설정
- 스토리북 render 수정
- 조건문 이후 hook 사용하는 문제 수정
- exhaustive deps 해결 및 해결을 위한 useCallback 적용
- 식물 등록 페이지 불필요한 effect 제거
=> refactor: eslint react hooks recommended 설정 및 리팩터링

backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java, backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java, backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java, backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java, backend/pium/src/main/java/com/official/pium/service/ReminderService.java, backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
- close #238 
이벤트가 적절하게 분리되었는지 확인 부탁드립니다.
=> refactor: 히스토리 이벤트 방식으로 수정

backend/pium/src/main/java/com/official/pium/domain/PetPlant.java, backend/pium/src/main/java/com/official/pium/service/PetPlantService.java, backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java, backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
- close #268 
사용자 시나리오 빼먹은사항 없는지 확인 부탁드립니다
=> fix: 반려 식물 정보 업데이트 시 lastWaterDate 검증조건 추가

frontend/src/apis/auth.ts, frontend/src/apis/history.ts, frontend/src/apis/pet.ts
- close #288 
credential 추가 및 filter에서 "" 삭제
=> hotfix: `crdential` 추가 및 history filter에 "" 제거

frontend/src/apis/auth.ts
- close #294 
`getSessionId`에 `includentials` 추가
=> refactor: getSessionId에 credentials 추가

backend/pium/src/docs/asciidoc/history.adoc, backend/pium/src/docs/asciidoc/petPlant.adoc, backend/pium/src/docs/asciidoc/reminder.adoc, backend/pium/src/main/java/com/official/pium/controller/HistoryController.java, backend/pium/src/main/java/com/official/pium/domain/History.java, backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java, backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java, backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java, backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java, backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepository.java, backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepositoryImpl.java, backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepository.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepositoryImpl.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java, backend/pium/src/main/java/com/official/pium/service/HistoryService.java, backend/pium/src/main/java/com/official/pium/service/MemberService.java, backend/pium/src/main/java/com/official/pium/service/PetPlantService.java, backend/pium/src/main/java/com/official/pium/service/ReminderService.java, backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java, backend/pium/src/main/resources/logback-spring.xml, backend/pium/src/main/resources/slack-notification-appender.xml, backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java, backend/pium/src/test/java/com/official/pium/domain/HistoryTest.java, backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
- close #297 
배포 전 백엔드 코드 리팩토링을 진행했습니다.
몹 프로그래밍 진행사항입니다.
=> refactor: 백엔드 코드 리팩터링

backend/pium/src/main/resources/slack-notification-prod-appender.xml
- close #301 
운영 서버 로그백 파일을 추가했씁니다. 누락 죄송 ㅜㅜ
ㅜㅜ
=> fix: 운영 서버 로그 알림 추가

frontend/src/components/@common/Icons/AccountCircle.tsx, frontend/src/components/@common/Navbar/index.tsx, frontend/src/pages/Login/Login.style.ts, frontend/src/pages/Login/index.tsx
- close #305 
로그인 페이지에 이미지를 추가했습니다!
navbar 디자인 조금 바뀌었습니다!
=> feat: 로그인 페이지에 이미지 추가

frontend/src/components/@common/Confirm/Confirm.style.ts, frontend/src/components/@common/Toast/Toast.style.ts, frontend/src/components/petPlant/PetPlantDetail/index.tsx, frontend/src/components/reminder/Card/index.tsx, frontend/src/hooks/useReminderHooks.ts, frontend/src/pages/Login/Login.style.ts
=> fix: 다음 물주기 dday가 양수일 때 며칠 전으로 표현

backend/pium/src/main/java/com/official/pium/admin/Registration.java, backend/pium/src/main/java/com/official/pium/domain/Garden.java, backend/pium/src/main/resources/db/migration/V3__add_garden_regist.sql, backend/pium/src/main/resources/sql/schema.sql
=> feat: 모두의정원, 식물 등록 요청 엔티티 추가

frontend/src/apis/dictionaryPlantRegistration.ts, frontend/src/apis/petPlant.ts
=> fix: formData 타입 적용 후 수정

.gitmodules, backend/pium/src/main/java/com/official/pium/domain/HistoryCategory.java, backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java, backend/pium/src/main/java/com/official/pium/event/history/HistoryEvents.java, backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepository.java, backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepositoryImpl.java, backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java, backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java, backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java, backend/pium/src/main/java/com/official/pium/service/MemberService.java, backend/pium/src/main/java/com/official/pium/service/PetPlantService.java, backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java, backend/pium/src/main/resources/db/migration/V5__modify_history_category.sql, backend/pium/src/main/resources/sql/schema.sql, backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java, backend/pium/src/test/resources/application.properties
- close #347 
- close #373 
- close #374 
- 쿼리를 정리했습니다.
- historyCategory 테이블 컬럼을 변경했습니다. (불필요한 컬럼 제거 및 유니크 컬럼 설정)
잘부탁드립니다.
=> refactor: 쿼리 개선

backend/pium/src/main/resources/templates/admin/dict/requests.html
- close #378 
- 기본 이미지만 뜨던 현상을 수정했습니다.
감사합니다..
=> fix: 사전식물 등록 요청 사진 변경

backend/pium/src/docs/asciidoc/petPlant.adoc, backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java, backend/pium/src/main/java/com/official/pium/domain/PetPlant.java, backend/pium/src/main/java/com/official/pium/service/PetPlantService.java, backend/pium/src/main/java/com/official/pium/service/PhotoManager.java, backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java, backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java, backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java, backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java, backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java, backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java, backend/pium/src/test/java/com/official/pium/util/PhotoS3ManagerTest.java
- close #373 
반려 식물 수정 시 이미지 수정도 가능하도록 추가 구현했습니다.
기존 테스트 잘못 수정했는지, 부족한 테스트 없는지 한번씩 확인해주시면 감사하겠습니다!
=> feat: 반려 식물 이미지 수정 기능

frontend/src/components/@common/Navbar/Navbar.style.ts, frontend/src/components/@common/Navbar/index.tsx, frontend/src/hooks/queries/auth/useLogin.ts, frontend/src/hooks/queries/auth/useWithdraw.ts, frontend/src/pages/@common/RootTemplate/index.tsx
- close #446
|버그|수정 후|
|:-:|:-:|
|![before](https://github.com/woowacourse-teams/2023-pium/assets/77872742/aba6412c-d90b-4fdf-ab1b-af19b1924e79)|![after](https://github.com/woowacourse-teams/2023-pium/assets/77872742/af1d60b5-1afc-425c-8bd8-951a87a5cd72)|
원인도 과정도 잃어버렸지만 결과만은 남았습니다 😭😭😭😭😭😭😭😭
=> fix: 내비게이션 바 버그 수정

backend/pium/src/main/resources/templates/admin/member/requests.html
- close #456 
form 태그의 method를 제거했습니다
=> fix: 어드민 post 수정

backend/pium/src/main/java/com/official/pium/controller/HttpCookieManager.java, backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java, backend/pium/src/test/java/com/official/pium/controller/HttpCookieManagerTest.java
- close #462 
쿠키 구분 변경했습니다...
사랑합니다
=> fix: 쿠키 요청 구분 보완

backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java, backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java, backend/pium/src/main/resources/db/migration/V8__session_group_drop_unique.sql, backend/pium/src/test/java/com/official/pium/repository/SessionGroupRepositoryTest.java
- close #464 
세션 만료시간 30분  -> 30일
세션 존재 유무 검증로직 수정
=> fix: 세션 조회 로직 변경

backend/pium/src/main/java/com/official/pium/controller/HttpCookieManager.java, backend/pium/src/main/resources/db/migration/V8__session_group_drop_unique.sql, backend/pium/src/test/java/com/official/pium/controller/HttpCookieManagerTest.java
- close #466 
쿠키 조회 시 ; 뒤에 공백이 있었네요..
=> fix: 쿠키 조회 로직 변경
